version: '3.9'

volumes:
  pptgame_api_local_postgres_data: {}
  pptgame_api_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: pptgame_api_local_django
    container_name: pptgame_api_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - .env
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    image: pptgame_api_production_postgres
    container_name: pptgame_api_local_postgres
    volumes:
      - pptgame_api_local_postgres_data:/var/lib/postgresql/data
      - pptgame_api_local_postgres_data_backups:/backups
    env_file:
      - .env
